### ISSUE TITLE
Bootstrap content not working with latest versions

### ISSUE THREAD

**Issue by eXistenZe** [2sic/dnn-theme-bootstrap4-instant#17] opened 2020-05-13 21:51 UTC
I have a previous BS4 version with working bootstrap.
I'm trying the latest version and most BS functionalities do not work (modals, accordions, etc).
CSS looks fine, but accordions are always expanded and do not change when clicked, and modals are fixed in the html position.

Using DNN 9.4 and 9.6.

**Comment by b-creative** [comment] 2020-05-14 01:46
Please upgrade to DNN 9.6.1

**Comment by eXistenZe** [comment] 2020-05-14 07:01
Already did that to fix jquery. Sorry for not mentioning it before.

**Comment by iJungleboy** [comment] 2020-05-14 07:29
@SirAjZellweger could you check this? It could just be a temporary bug with dnn 9.6 fixed in 9.6.1, but it could also be that we need to enhance something so it works with old and new jquery

**Comment by iJungleboy** [comment] 2020-05-15 11:17
Just fyi: from what we see the issue is that the standard CSS we build for the theme is optimized for the current need, and doesn't include all possible Bootstrap parts. Including all by default slows down the page and of course gets punished by Google PageSpeed. 
If you need them, you need to activate the Bootstrap Modules like this one: https://github.com/2sic/dnn-theme-bootstrap4-instant/blob/master/src/scss/theme.scss#L43

@SirAjZellweger will create a checklist how to go about this.

**Comment by eXistenZe** [comment] 2020-05-15 11:28
You could make these inclusions modular with a simple setting.

**Comment by iJungleboy** [comment] 2020-05-15 11:54
@eXistenZe I assume you mean a setting somewhere in DNN. That wouldn't work, since changing it means Webpack must run SASS again. So we can't just do this in a UI.

**Comment by eXistenZe** [comment] 2020-05-15 12:05
No no. A setting like changing primary and secondary color. Then running
webpack.

**Comment by iJungleboy** [comment] 2020-05-15 14:55
Since that mechanism with the imports is very Bootstrap Standard, we believe it's better to stick to that. Otherwise we add another layer of complexity.

**Comment by eXistenZe** [comment] 2020-05-15 14:57
If you can make a fool-proof guide to fix this, I'll take a look at it.

**Comment by eXistenZe** [comment] 2020-05-17 11:53
BTW, you have these two lines in the src/scss/_variables.scss
```
@import "../../node_modules/bootstrap/scss/functions";
@import "../../node_modules/bootstrap/scss/mixins";
```
The "mixins" folder exists, but the "functions" one does not.

**Comment by iJungleboy** [comment] 2020-05-18 07:34
@SirAjZellweger  could you check?

**Comment by SirAjZellweger** [comment] 2020-05-19 09:21
> BTW, you have these two lines in the src/scss/_variables.scss
> 
> ```
> @import "../../node_modules/bootstrap/scss/functions";
> @import "../../node_modules/bootstrap/scss/mixins";
> ```
> 
> The "mixins" folder exists, but the "functions" one does not.

These two lines import the following scss files:
* https://github.com/twbs/bootstrap/blob/master/scss/_functions.scss
* https://github.com/twbs/bootstrap/blob/master/scss/_mixins.scss

**Comment by iJungleboy** [comment] 2020-05-19 13:45
@eXistenZe Just fyi: the import statement imports the files mentioned above, not the folders. So the folders are not relevant. 

@SirAjZellweger created a checklist for future people looking for this: https://azing.org/2sxc/r/27gI3jSt

**Closed by iJungleboy** 2020-05-19 13:45 UTC
